/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package raytracer.kotlin

import raytracer.kotlin.scene.BasicScene
import java.io.File
import kotlin.system.measureTimeMillis

fun main() {
    val camera = Camera(1200, 900, Math.PI / 3.0)
    camera.transform = view(point(3.0, 3.0, -3.0), point(0.0, 0.5, 0.0), vector(0.0, 1.0, 0.0))

    val scene = BasicScene()

    val timeElapsed = measureTimeMillis {
        val canvas = camera.render(scene.getWorld())
        val ppm = PpmImage(canvas)
        val writer = File("renders/image.ppm").bufferedWriter()
        ppm.write(writer)
        writer.close()
    }

    println("Render time: ${timeElapsed}ms")
}
